### ISSUE TITLE
issue when build the project 

### ISSUE THREAD

**Issue by nguyenminhtuanfit** [DogusTeknoloji/springkafkadoc-example#2]
Tuans-MacBook-Pro:ui tuan$ npm install

up to date, audited 864 packages in 4s

182 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
Tuans-MacBook-Pro:ui tuan$ npm run build

> build
> eventcatalog build

> @eventcatalog/core@0.6.4 scripts:move-schema-for-download
> node scripts/move-schemas-for-download.js

> @eventcatalog/core@0.6.4 build
> next build && next export

info  - Linting and checking validity of types  
(node:90299) [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ...[zustand persist middleware] The given storage for item 'mosaic-theme' does not contain a 'removeItem' method, which will be required in v4.
file:///Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/mermaid/dist/mermaid.core.mjs:2
import { o } from "./mermaid-ae477ddf.js";
         ^
SyntaxError: Named export 'o' not found. The requested module './mermaid-ae477ddf.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './mermaid-ae477ddf.js';
const { o } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)

> Build error occurred
Error: Failed to collect page data for /events
    at /Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/next/dist/build/utils.js:916:15 {
  type: 'Error'
}
info  - Collecting page data .Error: Command failed: cross-env PROJECT_DIR=/Users/tuan/Desktop/document/springkafkadoc-example/ui npm run build
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at Command.<anonymous> (/Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/@eventcatalog/core/bin/eventcatalog.js:60:5)
    at Command.listener [as _actionHandler] (/Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/commander/index.js:1460:12)
    at Command.parse (/Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/commander/index.js:1292:10)
    at run (/Users/tuan/Desktop/document/springkafkadoc-example/ui/node_modules/@eventcatalog/core/bin/eventcatalog.js:115:7) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 90263,
  stdout: null,
  stderr: null
}

**Comment by nguyenminhtuanfit** [comment]
i am running v20.0.0 (nodejs)
